/* ============================================================================
   Seed data - roles, platforms, sample users, categories
   Run AFTER schema_sqlserver.sql
   NOTE: Password for every sample user is  Passw0rd!  (bcrypt hash placeholder
         below is generated by backend/utils/seed.py - use that script instead
         of this file if you want working logins out of the box).
   ============================================================================ */
USE kiosk;
GO

SET IDENTITY_INSERT dbo.ChangeFlowRoles ON;
INSERT INTO dbo.ChangeFlowRoles (RoleID, RoleName) VALUES
 (1, 'Requester'),
 (2, 'Platform Owner'),
 (3, 'PGC'),
 (4, 'Developer'),
 (5, 'Admin');
SET IDENTITY_INSERT dbo.ChangeFlowRoles OFF;
GO

INSERT INTO dbo.ChangeFlowPlatforms (PlatformName) VALUES
 ('Core Banking Platform'),
 ('Customer Mobile App'),
 ('Internal HR Portal');
GO

INSERT INTO dbo.ChangeFlowCategories (CategoryName, Type) VALUES
 ('New Feature', 'Enhancement'),
 ('Bug Fix', 'Enhancement'),
 ('New Project', 'Project'),
 ('Integration', 'Enhancement');
GO

PRINT 'Seed data inserted. Use backend/utils/seed.py to also create login users.';
